services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    command: npm run dev
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/artisan-assistant
      - JWT_SECRET=devsecret
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - backend

  ml:
    build: ./ml
    command: python embed_prototype.py
    volumes:
      - ./ml:/app

volumes:
  mongo-data:
